import type { ThemePreset } from './presets'

const lightDefault: ThemePreset = {
  id: 'default',
  name: 'Default',
  mode: 'light',
  vars: {},
}

/**
 * Aurora (light) — violet-blue atmospheric gradients over translucent dark surfaces.
 * This is the original "glass" look: deep purple-tinted base with indigo glows.
 */
const lightAurora: ThemePreset = {
  id: 'aurora',
  name: 'Aurora',
  mode: 'light',
  glass: true,
  vars: {
    'color-scheme': 'dark',
    '--background': '#0a0a14',
    '--foreground': 'rgba(255, 255, 255, 0.93)',
    '--card': 'rgba(255, 255, 255, 0.04)',
    '--card-foreground': 'rgba(255, 255, 255, 0.93)',
    '--popover': '#141423',
    '--popover-foreground': 'rgba(255, 255, 255, 0.93)',
    '--primary': '#6c7bff',
    '--primary-foreground': '#0a0a14',
    '--secondary': 'rgba(255, 255, 255, 0.06)',
    '--secondary-foreground': 'rgba(255, 255, 255, 0.93)',
    '--muted': 'rgba(255, 255, 255, 0.04)',
    '--muted-foreground': 'rgba(255, 255, 255, 0.6)',
    '--accent': 'rgba(255, 255, 255, 0.06)',
    '--accent-foreground': 'rgba(255, 255, 255, 0.93)',
    '--destructive': '#f87171',
    '--border': 'rgba(255, 255, 255, 0.08)',
    '--input': 'rgba(255, 255, 255, 0.06)',
    '--ring': '#6c7bff',
    '--destructive-foreground': '#fca5a5',
    '--info': '#6c7bff',
    '--info-foreground': '#a5b4ff',
    '--success': '#4ade80',
    '--success-foreground': '#86efac',
    '--warning': '#fbbf24',
    '--warning-foreground': '#fcd34d',
    '--sidebar': 'rgba(255, 255, 255, 0.03)',
    '--sidebar-foreground': 'rgba(255, 255, 255, 0.87)',
    '--sidebar-border': 'rgba(255, 255, 255, 0.06)',
    '--sidebar-accent': 'rgba(255, 255, 255, 0.06)',
    '--sidebar-accent-foreground': 'rgba(255, 255, 255, 0.93)',
    '--sidebar-primary': '#6c7bff',
    '--sidebar-primary-foreground': '#0a0a14',
    '--sidebar-ring': '#6c7bff',
    // Violet-blue atmospheric glows
    '--glow-1': 'rgba(108, 123, 255, 0.13)',
    '--glow-1-fade': 'rgba(108, 123, 255, 0.03)',
    '--glow-2': 'rgba(168, 85, 247, 0.08)',
    '--glow-2-fade': 'rgba(168, 85, 247, 0.02)',
    '--glow-3': 'rgba(124, 58, 237, 0.10)',
    '--glow-3-fade': 'rgba(124, 58, 237, 0.02)',
    '--glow-4': 'rgba(14, 165, 233, 0.09)',
    '--glow-4-fade': 'rgba(14, 165, 233, 0.02)',
  },
}

const lightGithub: ThemePreset = {
  id: 'github',
  name: 'GitHub',
  mode: 'light',
  vars: {
    '--background': '#ffffff',
    '--foreground': '#1f2328',
    '--card': '#ffffff',
    '--card-foreground': '#1f2328',
    '--popover': '#ffffff',
    '--popover-foreground': '#1f2328',
    '--primary': '#0969da',
    '--primary-foreground': '#ffffff',
    '--secondary': '#f6f8fa',
    '--secondary-foreground': '#1f2328',
    '--muted': '#f6f8fa',
    '--muted-foreground': '#656d76',
    '--accent': '#f6f8fa',
    '--accent-foreground': '#1f2328',
    '--destructive': '#cf222e',
    '--border': '#d1d9e0',
    '--input': '#d1d9e0',
    '--ring': '#0969da',
    '--destructive-foreground': '#a40e26',
    '--info': '#0969da',
    '--info-foreground': '#0550ae',
    '--success': '#1a7f37',
    '--success-foreground': '#116329',
    '--warning': '#9a6700',
    '--warning-foreground': '#7d4e00',
    '--sidebar': '#f6f8fa',
    '--sidebar-foreground': '#1f2328',
    '--sidebar-border': '#d1d9e0',
    '--sidebar-accent': '#eaeef2',
    '--sidebar-accent-foreground': '#1f2328',
    '--sidebar-primary': '#0969da',
    '--sidebar-primary-foreground': '#ffffff',
    '--sidebar-ring': '#0969da',
  },
}

const lightCatppuccinLatte: ThemePreset = {
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  mode: 'light',
  vars: {
    '--background': '#eff1f5',
    '--foreground': '#4c4f69',
    '--card': '#e6e9ef',
    '--card-foreground': '#4c4f69',
    '--popover': '#e6e9ef',
    '--popover-foreground': '#4c4f69',
    '--primary': '#7287fd',
    '--primary-foreground': '#eff1f5',
    '--secondary': '#dce0e8',
    '--secondary-foreground': '#4c4f69',
    '--muted': '#dce0e8',
    '--muted-foreground': '#6c6f85',
    '--accent': '#dce0e8',
    '--accent-foreground': '#4c4f69',
    '--destructive': '#d20f39',
    '--border': '#ccd0da',
    '--input': '#ccd0da',
    '--ring': '#7287fd',
    '--destructive-foreground': '#d20f39',
    '--info': '#1e66f5',
    '--info-foreground': '#1e66f5',
    '--success': '#40a02b',
    '--success-foreground': '#40a02b',
    '--warning': '#df8e1d',
    '--warning-foreground': '#df8e1d',
    '--sidebar': '#e6e9ef',
    '--sidebar-foreground': '#4c4f69',
    '--sidebar-border': '#ccd0da',
    '--sidebar-accent': '#dce0e8',
    '--sidebar-accent-foreground': '#4c4f69',
    '--sidebar-primary': '#7287fd',
    '--sidebar-primary-foreground': '#eff1f5',
    '--sidebar-ring': '#7287fd',
  },
}

const lightRosePine: ThemePreset = {
  id: 'rose-pine-dawn',
  name: 'Ros\u00e9 Pine Dawn',
  mode: 'light',
  vars: {
    '--background': '#faf4ed',
    '--foreground': '#575279',
    '--card': '#fffaf3',
    '--card-foreground': '#575279',
    '--popover': '#fffaf3',
    '--popover-foreground': '#575279',
    '--primary': '#907aa9',
    '--primary-foreground': '#faf4ed',
    '--secondary': '#f2e9e1',
    '--secondary-foreground': '#575279',
    '--muted': '#f2e9e1',
    '--muted-foreground': '#797593',
    '--accent': '#f2e9e1',
    '--accent-foreground': '#575279',
    '--destructive': '#b4637a',
    '--border': '#dfdad9',
    '--input': '#dfdad9',
    '--ring': '#907aa9',
    '--destructive-foreground': '#b4637a',
    '--info': '#286983',
    '--info-foreground': '#286983',
    '--success': '#56949f',
    '--success-foreground': '#56949f',
    '--warning': '#ea9d34',
    '--warning-foreground': '#ea9d34',
    '--sidebar': '#fffaf3',
    '--sidebar-foreground': '#575279',
    '--sidebar-border': '#dfdad9',
    '--sidebar-accent': '#f2e9e1',
    '--sidebar-accent-foreground': '#575279',
    '--sidebar-primary': '#907aa9',
    '--sidebar-primary-foreground': '#faf4ed',
    '--sidebar-ring': '#907aa9',
  },
}

/** Terminal (light) — vintage printout: warm off-white paper with green ink. */
const lightTerminal: ThemePreset = {
  id: 'terminal',
  name: 'Terminal',
  mode: 'light',
  vars: {
    '--background': '#f4f3ee',
    '--foreground': '#1a2e1a',
    '--card': '#eceae4',
    '--card-foreground': '#1a2e1a',
    '--popover': '#eceae4',
    '--popover-foreground': '#1a2e1a',
    '--primary': '#16a34a',
    '--primary-foreground': '#f4f3ee',
    '--secondary': '#e4e2db',
    '--secondary-foreground': '#1a2e1a',
    '--muted': '#e4e2db',
    '--muted-foreground': '#4d6a4d',
    '--accent': '#e4e2db',
    '--accent-foreground': '#1a2e1a',
    '--destructive': '#b91c1c',
    '--border': '#c9c6bc',
    '--input': '#c9c6bc',
    '--ring': '#16a34a',
    '--destructive-foreground': '#991b1b',
    '--info': '#0d7c66',
    '--info-foreground': '#0d7c66',
    '--success': '#16a34a',
    '--success-foreground': '#15803d',
    '--warning': '#a16207',
    '--warning-foreground': '#854d0e',
    '--sidebar': '#eceae4',
    '--sidebar-foreground': '#1a2e1a',
    '--sidebar-border': '#c9c6bc',
    '--sidebar-accent': '#e4e2db',
    '--sidebar-accent-foreground': '#1a2e1a',
    '--sidebar-primary': '#16a34a',
    '--sidebar-primary-foreground': '#f4f3ee',
    '--sidebar-ring': '#16a34a',
  },
}

const lightNord: ThemePreset = {
  id: 'nord',
  name: 'Nord',
  mode: 'light',
  vars: {
    '--background': '#eceff4',
    '--foreground': '#2e3440',
    '--card': '#e5e9f0',
    '--card-foreground': '#2e3440',
    '--popover': '#e5e9f0',
    '--popover-foreground': '#2e3440',
    '--primary': '#5e81ac',
    '--primary-foreground': '#eceff4',
    '--secondary': '#d8dee9',
    '--secondary-foreground': '#2e3440',
    '--muted': '#d8dee9',
    '--muted-foreground': '#4c566a',
    '--accent': '#d8dee9',
    '--accent-foreground': '#2e3440',
    '--destructive': '#bf616a',
    '--border': '#c4cad6',
    '--input': '#c4cad6',
    '--ring': '#5e81ac',
    '--destructive-foreground': '#bf616a',
    '--info': '#5e81ac',
    '--info-foreground': '#5e81ac',
    '--success': '#a3be8c',
    '--success-foreground': '#a3be8c',
    '--warning': '#ebcb8b',
    '--warning-foreground': '#d08770',
    '--sidebar': '#e5e9f0',
    '--sidebar-foreground': '#2e3440',
    '--sidebar-border': '#c4cad6',
    '--sidebar-accent': '#d8dee9',
    '--sidebar-accent-foreground': '#2e3440',
    '--sidebar-primary': '#5e81ac',
    '--sidebar-primary-foreground': '#eceff4',
    '--sidebar-ring': '#5e81ac',
  },
}

const lightSolarized: ThemePreset = {
  id: 'solarized',
  name: 'Solarized',
  mode: 'light',
  vars: {
    '--background': '#fdf6e3',
    '--foreground': '#657b83',
    '--card': '#eee8d5',
    '--card-foreground': '#657b83',
    '--popover': '#eee8d5',
    '--popover-foreground': '#657b83',
    '--primary': '#268bd2',
    '--primary-foreground': '#fdf6e3',
    '--secondary': '#eee8d5',
    '--secondary-foreground': '#586e75',
    '--muted': '#eee8d5',
    '--muted-foreground': '#93a1a1',
    '--accent': '#eee8d5',
    '--accent-foreground': '#586e75',
    '--destructive': '#dc322f',
    '--border': '#d6cdb7',
    '--input': '#d6cdb7',
    '--ring': '#268bd2',
    '--destructive-foreground': '#dc322f',
    '--info': '#268bd2',
    '--info-foreground': '#268bd2',
    '--success': '#859900',
    '--success-foreground': '#859900',
    '--warning': '#b58900',
    '--warning-foreground': '#b58900',
    '--sidebar': '#eee8d5',
    '--sidebar-foreground': '#657b83',
    '--sidebar-border': '#d6cdb7',
    '--sidebar-accent': '#e6dfca',
    '--sidebar-accent-foreground': '#586e75',
    '--sidebar-primary': '#268bd2',
    '--sidebar-primary-foreground': '#fdf6e3',
    '--sidebar-ring': '#268bd2',
  },
}

const lightGruvbox: ThemePreset = {
  id: 'gruvbox',
  name: 'Gruvbox',
  mode: 'light',
  vars: {
    '--background': '#fbf1c7',
    '--foreground': '#3c3836',
    '--card': '#f2e5bc',
    '--card-foreground': '#3c3836',
    '--popover': '#f2e5bc',
    '--popover-foreground': '#3c3836',
    '--primary': '#d65d0e',
    '--primary-foreground': '#fbf1c7',
    '--secondary': '#ebdbb2',
    '--secondary-foreground': '#3c3836',
    '--muted': '#ebdbb2',
    '--muted-foreground': '#665c54',
    '--accent': '#ebdbb2',
    '--accent-foreground': '#3c3836',
    '--destructive': '#cc241d',
    '--border': '#d5c4a1',
    '--input': '#d5c4a1',
    '--ring': '#d65d0e',
    '--destructive-foreground': '#cc241d',
    '--info': '#458588',
    '--info-foreground': '#458588',
    '--success': '#98971a',
    '--success-foreground': '#98971a',
    '--warning': '#d79921',
    '--warning-foreground': '#d79921',
    '--sidebar': '#f2e5bc',
    '--sidebar-foreground': '#3c3836',
    '--sidebar-border': '#d5c4a1',
    '--sidebar-accent': '#ebdbb2',
    '--sidebar-accent-foreground': '#3c3836',
    '--sidebar-primary': '#d65d0e',
    '--sidebar-primary-foreground': '#fbf1c7',
    '--sidebar-ring': '#d65d0e',
  },
}

const lightTokyoNight: ThemePreset = {
  id: 'tokyo-night',
  name: 'Tokyo Night',
  mode: 'light',
  vars: {
    '--background': '#d5d6db',
    '--foreground': '#343b59',
    '--card': '#cbccd1',
    '--card-foreground': '#343b59',
    '--popover': '#cbccd1',
    '--popover-foreground': '#343b59',
    '--primary': '#34548a',
    '--primary-foreground': '#d5d6db',
    '--secondary': '#c4c5ca',
    '--secondary-foreground': '#343b59',
    '--muted': '#c4c5ca',
    '--muted-foreground': '#6172b0',
    '--accent': '#c4c5ca',
    '--accent-foreground': '#343b59',
    '--destructive': '#8c4351',
    '--border': '#b4b5b9',
    '--input': '#b4b5b9',
    '--ring': '#34548a',
    '--destructive-foreground': '#8c4351',
    '--info': '#34548a',
    '--info-foreground': '#34548a',
    '--success': '#33635c',
    '--success-foreground': '#33635c',
    '--warning': '#8f5e15',
    '--warning-foreground': '#8f5e15',
    '--sidebar': '#cbccd1',
    '--sidebar-foreground': '#343b59',
    '--sidebar-border': '#b4b5b9',
    '--sidebar-accent': '#c4c5ca',
    '--sidebar-accent-foreground': '#343b59',
    '--sidebar-primary': '#34548a',
    '--sidebar-primary-foreground': '#d5d6db',
    '--sidebar-ring': '#34548a',
  },
}

export const LIGHT_PRESETS: readonly ThemePreset[] = [
  lightDefault,
  lightAurora,
  lightGithub,
  lightTerminal,
  lightNord,
  lightSolarized,
  lightGruvbox,
  lightCatppuccinLatte,
  lightTokyoNight,
  lightRosePine,
]
