import { memo, useCallback, useEffect, useMemo, useRef, useState, type RefObject } from "react";
import { Zap } from "lucide-react";
import { useCodexSession } from "../hooks/useCodexSession";
import { ComposerPanel } from "./ComposerPanel";
import { InteractionCard } from "./chat/InteractionCard";
import { VirtualizedTimeline } from "./chat/VirtualizedTimeline";
import { UnifiedTimelineRowView } from "./chat/UnifiedTimelineRow";
import { estimateUnifiedTimelineRowHeight, type UnifiedTimelineRenderRow } from "./chat/unified-timeline-model";
import type { ModelOption } from "../lib/models";
import type { PermissionMode } from "../types/app";
import type { CodexCollaborationMode, CodexModelEntry } from "@shared/ipc";
import type { CodexMessageItem } from "../hooks/useCodexSession";
import { deriveSessionTitleFromPrompt, looksAutoGeneratedSessionTitle } from "../lib/app-session-utils";
import { buildCodexMessagesFromThread, extractThreadFromResumeResponse } from "../lib/codex-thread-transcript";
import {
  buildCodexBackgroundAgents,
  buildCodexBackgroundAgentsFromChildThreads,
  buildCodexBackgroundAgentsFromMessages,
  extractCodexTodoItemsFromMessages,
  filterOutCurrentCodexThreadAgent,
  projectCodexSessionPresentation,
} from "../lib/session-presentation";
import { extractReviewChangesFiles } from "../lib/timeline-row-grouping";
import { selectPendingPermissionDockData, selectPendingQuestionDockData, useUnifiedRuntimeStore } from "../state/unified-runtime-store";

interface Props {
  directory: string;
  sessionStorageKey: string;
  titleLocked?: boolean;
  onExit: () => void;
  onFirstMessage?: () => void;
  onTitleChange?: (title: string) => void;
  notifyOnAwaitingInput?: boolean;
  subagentSystemNotificationsEnabled?: boolean;
  codexAccessMode?: string;
  defaultReasoningEffort?: string;
  permissionMode: PermissionMode;
  onPermissionModeChange: (mode: PermissionMode) => void;
  codexPath?: string;
  codexArgs?: string;
  // Branch props (forwarded to ComposerPanel)
  branchMenuOpen: boolean;
  setBranchMenuOpen: (updater: (value: boolean) => boolean) => void;
  branchControlWidthCh: number;
  branchLoading: boolean;
  branchSwitching: boolean;
  hasActiveProject: boolean;
  branchCurrent?: string;
  branchDisplayValue: string;
  branchSearchInputRef: RefObject<HTMLInputElement | null>;
  branchQuery: string;
  setBranchQuery: (value: string) => void;
  branchActionError: string | null;
  clearBranchActionError: () => void;
  checkoutBranch: (name: string) => void | Promise<void>;
  filteredBranches: string[];
  openBranchCreateModal: () => void | Promise<void>;
  onOpenFileReference?: (reference: string) => void;
  browserModeEnabled?: boolean;
  setBrowserModeEnabled?: (enabled: boolean) => void;
}

const CODEX_PROVIDER_ID = "codex";
const CODEX_PROVIDER_NAME = "Codex";

function codexModelsToOptions(models: { id: string; model: string; name: string; isDefault: boolean }[]): ModelOption[] {
  return models.map((m) => ({
    key: `${CODEX_PROVIDER_ID}/${m.model}`,
    providerID: CODEX_PROVIDER_ID,
    modelID: m.model,
    providerName: CODEX_PROVIDER_NAME,
    modelName: m.name,
    variants: [],
  }));
}

const MAX_AUTO_TITLE_PROMPT_CHARS = 1200;
function cleanPromptForAutoTitle(prompt: string) {
  if (!prompt) {
    return "";
  }
  const withoutImages = prompt.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  const normalized = withoutSkills.replace(/\s+/g, " ").trim();
  return normalized.length > MAX_AUTO_TITLE_PROMPT_CHARS
    ? normalized.slice(0, MAX_AUTO_TITLE_PROMPT_CHARS)
    : normalized;
}

function normalizeGeneratedTitle(title: string | undefined) {
  const cleaned = title?.replace(/\s+/g, " ").trim() ?? "";
  return cleaned || null;
}

type CodexUsageAlert = {
  title: string;
  body: string;
};

function getCodexUsageAlert(lastError: string | undefined): CodexUsageAlert | null {
  const raw = lastError?.trim();
  if (!raw) {
    return null;
  }
  const normalized = raw.toLowerCase();
  const quotaSignals = [
    "insufficient quota",
    "quota exceeded",
    "out of credits",
    "no credits",
    "usage limit",
    "billing",
    "payment required",
    "credits remaining",
    "reached your current usage limit",
  ];
  if (!quotaSignals.some((signal) => normalized.includes(signal))) {
    return null;
  }
  return {
    title: "Codex usage unavailable",
    body: "This account appears to have no remaining Codex credits or usage. Add credits or switch account, then retry the session.",
  };
}

const CodexConversationView = memo(function CodexConversationView({
  visibleMessages,
  trailingReasoning,
  isStreaming,
  scrollContainerRef,
  messagesEndRef,
  handleScroll,
  showEmptyState,
  onOpenFileReference,
  sessionId,
}: {
  visibleMessages: CodexMessageItem[];
  trailingReasoning?: CodexMessageItem;
  isStreaming: boolean;
  scrollContainerRef: RefObject<HTMLDivElement | null>;
  messagesEndRef: RefObject<HTMLDivElement | null>;
  handleScroll: () => void;
  showEmptyState: boolean;
  onOpenFileReference?: (reference: string) => void;
  sessionId?: string;
}) {
  const rows = useMemo<UnifiedTimelineRenderRow[]>(() => {
    const nextMessages = trailingReasoning ? [...visibleMessages, trailingReasoning] : visibleMessages;
    return projectCodexSessionPresentation(nextMessages, isStreaming).rows;
  }, [trailingReasoning, visibleMessages, isStreaming]);

  return (
    <VirtualizedTimeline
      rows={rows}
      scrollRef={scrollContainerRef}
      className="messages-scroll codex-messages"
      ariaLabel="codex conversation"
      onScroll={handleScroll}
      estimateSize={estimateUnifiedTimelineRowHeight}
      virtualize={false}
      sessionId={sessionId}
      emptyState={
        showEmptyState ? (
          <div className="center-pane-rail">
            <div className="codex-empty">
              <Zap size={24} color="var(--text-muted)" />
              <span>Send a prompt to start coding with Codex.</span>
            </div>
          </div>
        ) : undefined
      }
      renderRow={(row) => (
        <div className="center-pane-rail center-pane-rail--row">
          <UnifiedTimelineRowView key={row.id} row={row} onOpenFileReference={onOpenFileReference} />
        </div>
      )}
      footer={
        <>
          <div className="center-pane-rail center-pane-rail--row">
            <div ref={messagesEndRef} />
          </div>
        </>
      }
    />
  );
});

export function CodexPane({
  directory,
  sessionStorageKey,
  titleLocked = false,
  onFirstMessage,
  onTitleChange,
  notifyOnAwaitingInput,
  subagentSystemNotificationsEnabled,
  codexAccessMode,
  defaultReasoningEffort,
  permissionMode,
  onPermissionModeChange,
  codexPath,
  codexArgs,
  branchMenuOpen,
  setBranchMenuOpen,
  branchControlWidthCh,
  branchLoading,
  branchSwitching,
  hasActiveProject,
  branchCurrent,
  branchDisplayValue,
  branchSearchInputRef,
  branchQuery,
  setBranchQuery,
  branchActionError,
  clearBranchActionError,
  checkoutBranch,
  filteredBranches,
  openBranchCreateModal,
  onOpenFileReference,
  browserModeEnabled = false,
  setBrowserModeEnabled,
}: Props) {
  const codexRuntime = useUnifiedRuntimeStore((state) => state.codexSessions[sessionStorageKey] ?? null);
  const {
    connectionStatus,
    thread,
    messages,
    pendingApproval,
    pendingUserInput,
    isStreaming,
    lastError,
    threadName,
    planItems,
    dismissedPlanIds,
    connect,
    startThread,
    sendMessage,
    steerMessage,
    approveAction,
    denyAction,
    respondToUserInput,
    rejectUserInput,
    interruptTurn,
    acceptPlan,
    submitPlanChanges,
    dismissPlan,
    isSubagentThread,
    subagents,
    activeSubagentThreadId,
    subagentMessages,
    openSubagentThread,
    closeSubagentThread,
  } = useCodexSession(directory, sessionStorageKey, { codexPath, codexArgs });

  // Derive plan readiness from message list instead of from event timing.
  // A plan is ready when:
  //   - the last tool item with toolType 'plan' exists and has non-empty output
  //   - its status is not 'error'
  //   - streaming is done (isStreaming is false)
  //   - no user message follows the plan item in the list
  //   - the plan item ID has not been dismissed
  const activePlanItem = useMemo(() => {
    if (isStreaming) return null;
    // Find the last plan tool item
    let lastPlanIdx = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      const m = messages[i];
      if (m.kind === "tool" && m.toolType === "plan") {
        lastPlanIdx = i;
        break;
      }
    }
    if (lastPlanIdx < 0) return null;
    const planItem = messages[lastPlanIdx];
    if (planItem.kind !== "tool") return null;
    // Must have non-empty output
    if (!planItem.output || planItem.output.trim().length === 0) return null;
    // Must not have failed
    if (planItem.status === "error") return null;
    // Must not be dismissed
    if (dismissedPlanIds.has(planItem.id)) return null;
    // Must not have a user message after it
    const hasUserMessageAfter = messages.slice(lastPlanIdx + 1).some(
      (m) => m.kind === "message" && m.role === "user",
    );
    if (hasUserMessageAfter) return null;
    return planItem;
  }, [messages, isStreaming, dismissedPlanIds]);

  const planReady = activePlanItem !== null;

  const [input, setInput] = useState("");
  const [selectedModel, setSelectedModel] = useState<string | undefined>(undefined);
  const [codexModels, setCodexModels] = useState<CodexModelEntry[]>([]);
  const [modelSelectOptions, setModelSelectOptions] = useState<ModelOption[]>([]);
  const [selectedReasoningEffort, setSelectedReasoningEffort] = useState<string | undefined>(undefined);
  const [isPlanMode, setIsPlanMode] = useState(false);
  const [todoOpen, setTodoOpen] = useState(false);
  const [archivedBackgroundAgentIds, setArchivedBackgroundAgentIds] = useState<string[]>([]);
  const [subagentThreadMessages, setSubagentThreadMessages] = useState<Record<string, CodexMessageItem[]>>({});
  const [subagentThreadLoading, setSubagentThreadLoading] = useState<Record<string, boolean>>({});
  const [subagentThreadErrors, setSubagentThreadErrors] = useState<Record<string, string | null>>({});
  const [codexQueue, setCodexQueue] = useState<Array<{ id: string; text: string; timestamp: number }>>([]);
  const [codexSendingId, setCodexSendingId] = useState<string | undefined>();
  const [collaborationModes, setCollaborationModes] = useState<CodexCollaborationMode[]>([]);
  const [selectedCollabMode, setSelectedCollabMode] = useState<string | undefined>(undefined);
  const defaultCollaborationModeId = useMemo(
    () => collaborationModes.find((mode) => {
      const modeId = mode.id.trim().toLowerCase();
      const kind = mode.mode.trim().toLowerCase();
      return modeId === "default" || kind === "default";
    })?.id ?? "default",
    [collaborationModes],
  );
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  // Track when the current turn started for notification delay
  const turnStartedAt = useRef<number>(0);
  const titleLockedRef = useRef(titleLocked);
  const threadIdRef = useRef<string | null>(thread?.id ?? null);
  const hasRequestedAutoTitleRef = useRef(false);
  // Auto-connect on mount (handles React 18 StrictMode double-mount)
  useEffect(() => {
    let cancelled = false;
    const autoConnect = async () => {
      // Small delay to survive StrictMode unmount/remount cycle
      await new Promise((r) => setTimeout(r, 50));
      if (cancelled) return;
      void connect();
    };
    void autoConnect();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-start thread when connected and no thread exists
  useEffect(() => {
    if (connectionStatus === "connected" && !thread) {
      const allowFullAccess = permissionMode === "yolo-write" || codexAccessMode === "full-access";
      const sandbox = allowFullAccess ? "danger-full-access" : "read-only";
      const approvalPolicy = allowFullAccess ? "never" : "on-request";
      void startThread({ title: "Orxa Code Session", sandbox, approvalPolicy });
    }
  }, [codexAccessMode, connectionStatus, permissionMode, startThread, thread]);

  // Load models and collaboration modes when connected
  useEffect(() => {
    if (connectionStatus === "connected" && window.orxa?.codex) {
      void window.orxa.codex.listModels().then((rawModels) => {
        setCodexModels(rawModels);
        const options = codexModelsToOptions(rawModels);
        setModelSelectOptions(options);
        // Pre-select default or first model if none selected
        if (!selectedModel && options.length > 0) {
          const defaultModel = rawModels.find((m) => m.isDefault);
          const defaultKey = defaultModel ? `${CODEX_PROVIDER_ID}/${defaultModel.model}` : options[0].key;
          setSelectedModel(defaultKey);
        }
      });
      // Load collaboration modes
      void window.orxa.codex.listCollaborationModes().then((modes) => {
        setCollaborationModes(modes);
      }).catch(() => {
        // Non-fatal — server may not support this
      });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [connectionStatus]);

  const selectedModelID = useMemo(
    () => selectedModel
      ? selectedModel.startsWith(`${CODEX_PROVIDER_ID}/`)
        ? selectedModel.slice(CODEX_PROVIDER_ID.length + 1)
        : selectedModel
      : undefined,
    [selectedModel],
  );

  const selectedCodexModel = useMemo(
    () => codexModels.find((model) => model.model === selectedModelID || model.id === selectedModelID),
    [codexModels, selectedModelID],
  );

  const reasoningEffortOptions = useMemo(
    () => selectedCodexModel?.supportedReasoningEfforts ?? [],
    [selectedCodexModel],
  );

  useEffect(() => {
    if (reasoningEffortOptions.length === 0) {
      if (selectedReasoningEffort !== undefined) {
        setSelectedReasoningEffort(undefined);
      }
      return;
    }
    if (selectedReasoningEffort && reasoningEffortOptions.includes(selectedReasoningEffort)) {
      return;
    }
    const preferredEffort = defaultReasoningEffort && reasoningEffortOptions.includes(defaultReasoningEffort)
      ? defaultReasoningEffort
      : undefined;
    const nextEffort = preferredEffort
      ?? selectedCodexModel?.defaultReasoningEffort
      ?? reasoningEffortOptions[0];
    setSelectedReasoningEffort(nextEffort || undefined);
  }, [defaultReasoningEffort, reasoningEffortOptions, selectedCodexModel?.defaultReasoningEffort, selectedReasoningEffort]);

  // Scroll tracking & auto-scroll are now handled universally by
  // VirtualizedTimeline via the sessionId prop. Keep a no-op callback
  // for the onScroll slot so external scroll listeners still attach.
  const handleScroll = useCallback(() => {}, []);

  useEffect(() => {
    titleLockedRef.current = titleLocked;
  }, [titleLocked]);

  useEffect(() => {
    threadIdRef.current = thread?.id ?? null;
    hasRequestedAutoTitleRef.current = false;
  }, [thread?.id, sessionStorageKey]);

  // Thread name -> sidebar title
  useEffect(() => {
    if (threadName && onTitleChange) {
      onTitleChange(threadName);
    }
  }, [threadName, onTitleChange]);

  useEffect(() => {
    if (threadName && !looksAutoGeneratedSessionTitle(threadName)) {
      hasRequestedAutoTitleRef.current = true;
    }
  }, [threadName]);

  // Notifications for codex awaiting states — deduplicated (one notification per state transition)
  const lastNotifiedRef = useRef<string | null>(null);
  useEffect(() => {
    if (!notifyOnAwaitingInput || document.hasFocus()) return;
    const visibleApproval = permissionMode === "yolo-write" ? null : pendingApproval;
    // Derive a key for the current awaiting state
    const key = visibleApproval
      ? `approval:${visibleApproval.itemId ?? visibleApproval.id}`
      : pendingUserInput
        ? `input:${pendingUserInput.itemId ?? pendingUserInput.id}`
        : planReady
          ? "plan"
          : null;
    if (!key || key === lastNotifiedRef.current) return;
    lastNotifiedRef.current = key;
    // Skip subagent notifications if disabled
    if (!subagentSystemNotificationsEnabled) {
      const eventThreadId = visibleApproval?.threadId ?? pendingUserInput?.threadId;
      if (eventThreadId && isSubagentThread(eventThreadId)) return;
    }
    // Only notify if agent has been working > 60s
    const MIN_WORKING_DURATION_MS = 60_000;
    if (turnStartedAt.current > 0 && Date.now() - turnStartedAt.current < MIN_WORKING_DURATION_MS) return;

    const body = planReady ? "Plan is ready for review" : pendingUserInput ? "Agent is asking a question" : "Agent needs permission to continue";
    new Notification("Orxa Code", { body, silent: false }).onclick = () => window.focus();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingApproval, pendingUserInput, permissionMode, planReady]);

  const queueCodexMessage = useCallback((text: string) => {
    const trimmed = text.trim();
    if (!trimmed) return;
    const id = `cq:${Date.now().toString(36)}:${Math.random().toString(36).slice(2, 8)}`;
    setCodexQueue((current) => [...current, { id, text: trimmed, timestamp: Date.now() }]);
    setInput("");
  }, []);

  const removeCodexQueued = useCallback((id: string) => {
    setCodexQueue((current) => current.filter((item) => item.id !== id));
  }, []);

  // Auto-send first queued message when Codex session becomes idle
  const prevCodexStreamingRef = useRef(false);
  useEffect(() => {
    const wasBusy = prevCodexStreamingRef.current;
    prevCodexStreamingRef.current = isStreaming;
    if (wasBusy && !isStreaming && codexQueue.length > 0 && !codexSendingId) {
      const first = codexQueue[0];
      if (first) {
        setCodexSendingId(first.id);
        void sendMessage(first.text).then(() => {
          setCodexSendingId(undefined);
        });
        setCodexQueue((current) => current.filter((m) => m.id !== first.id));
      }
    }
  }, [isStreaming, codexQueue, codexSendingId, sendMessage]);

  const editCodexQueued = useCallback((id: string) => {
    setCodexQueue((current) => {
      const item = current.find((m) => m.id === id);
      if (item) {
        setInput(item.text);
      }
      return current.filter((m) => m.id !== id);
    });
  }, []);

  const requestCodexTitle = useCallback(
    async (targetThreadId: string, requestedTitle: string) => {
      const normalized = normalizeGeneratedTitle(requestedTitle);
      if (!normalized || !window.orxa?.codex) {
        return false;
      }
      if (titleLockedRef.current || threadIdRef.current !== targetThreadId) {
        return false;
      }
      await window.orxa.codex.setThreadName(targetThreadId, normalized);
      if (titleLockedRef.current || threadIdRef.current !== targetThreadId) {
        return false;
      }
      onTitleChange?.(normalized);
      return true;
    },
    [onTitleChange],
  );

  const queueAutoTitleGeneration = useCallback(
    (prompt: string, targetThreadId: string) => {
      if (hasRequestedAutoTitleRef.current || titleLockedRef.current || !window.orxa?.codex) {
        return;
      }
      if (messages.some((item) => item.kind === "message" && item.role === "user")) {
        return;
      }
      if (threadName && !looksAutoGeneratedSessionTitle(threadName)) {
        return;
      }

      const cleanedPrompt = cleanPromptForAutoTitle(prompt);
      if (!cleanedPrompt) {
        return;
      }

      hasRequestedAutoTitleRef.current = true;

      void (async () => {
        try {
          const metadata = await window.orxa.codex.generateRunMetadata(directory, cleanedPrompt);
          const applied = await requestCodexTitle(targetThreadId, metadata.title);
          if (applied) {
            return;
          }
        } catch {
          // Fall back to prompt-derived naming if Codex metadata generation fails.
        }

        try {
          await requestCodexTitle(targetThreadId, deriveSessionTitleFromPrompt(prompt));
        } catch {
          // Leave the session on its default title if rename persistence fails.
        }
      })();
    },
    [directory, messages, requestCodexTitle, threadName],
  );

  const buildTurnOptions = useCallback(() => {
    onFirstMessage?.();
    const opts: { model?: string; effort?: string; collaborationMode?: string } = {};
    if (selectedModelID) opts.model = selectedModelID;
    if (selectedReasoningEffort) opts.effort = selectedReasoningEffort;
    if (selectedCollabMode) opts.collaborationMode = selectedCollabMode;
    return opts;
  }, [onFirstMessage, selectedCollabMode, selectedModelID, selectedReasoningEffort]);

  const sendTextNow = useCallback(async (text: string, options?: { interruptIfBusy?: boolean }) => {
    const trimmed = text.trim();
    if (!trimmed || !thread) {
      return false;
    }
    if (isStreaming) {
      if (!options?.interruptIfBusy) {
        return false;
      }
      await interruptTurn();
    }
    queueAutoTitleGeneration(trimmed, thread.id);
    const opts = buildTurnOptions();
    turnStartedAt.current = Date.now();
    await sendMessage(trimmed, Object.keys(opts).length > 0 ? opts : undefined);
    return true;
  }, [buildTurnOptions, interruptTurn, isStreaming, queueAutoTitleGeneration, sendMessage, thread]);

  const sendPrompt = useCallback(async () => {
    const trimmed = input.trim();
    if (!trimmed) return;
    setInput("");
    const sent = await sendTextNow(trimmed);
    if (!sent) {
      setInput(trimmed);
    }
  }, [input, sendTextNow]);

  const abortActiveSession = useCallback(async () => {
    await interruptTurn();
  }, [interruptTurn]);

  const autoApprovedRequestIdRef = useRef<number | null>(null);
  useEffect(() => {
    if (!pendingApproval) {
      autoApprovedRequestIdRef.current = null;
      return;
    }
    if (permissionMode !== "yolo-write") {
      return;
    }
    if (autoApprovedRequestIdRef.current === pendingApproval.id) {
      return;
    }
    autoApprovedRequestIdRef.current = pendingApproval.id;
    const decision = pendingApproval.availableDecisions.includes("acceptForSession") ? "acceptForSession" : "accept";
    void approveAction(decision);
  }, [approveAction, pendingApproval, permissionMode]);

  // ESC key handler — interrupt active turn when streaming
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isStreaming) {
        void abortActiveSession();
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isStreaming, abortActiveSession]);

  // Map pendingApproval -> PermissionDock props
  const pendingPermissionData = selectPendingPermissionDockData({
    provider: "codex",
    sessionKey: sessionStorageKey,
    permissionMode,
  });
  const permissionDockProps = pendingPermissionData
    ? {
        description: pendingPermissionData.description,
        filePattern: pendingPermissionData.filePattern,
        command: pendingPermissionData.command,
        onDecide: (decision: "allow_once" | "allow_always" | "reject") => {
          if (decision === "allow_once") {
            void approveAction("accept");
          } else if (decision === "allow_always") {
            void approveAction("acceptForSession");
          } else {
            void denyAction();
          }
        },
      }
    : null;

  const pendingQuestionData = selectPendingQuestionDockData({
    provider: "codex",
    sessionKey: sessionStorageKey,
  });
  const questionDockProps = pendingQuestionData
    ? {
        questions: pendingQuestionData.questions,
        onSubmit: (rawAnswers: Record<string, string | string[]>) => {
          // Convert QuestionDock answers to the Codex CLI format: { [questionId]: { answers: string[] } }
          const codexAnswers: Record<string, { answers: string[] }> = {};
          for (const [qId, val] of Object.entries(rawAnswers)) {
            codexAnswers[qId] = { answers: Array.isArray(val) ? val : [val] };
          }
          void respondToUserInput(codexAnswers);
        },
        onReject: () => {
          void rejectUserInput();
        },
      }
    : null;
  const pendingPlanProps = planReady
    ? {
        onAccept: () => {
          setIsPlanMode(false);
          setSelectedCollabMode(defaultCollaborationModeId);
          void acceptPlan({
            collaborationMode: defaultCollaborationModeId,
            model: selectedModelID,
            effort: selectedReasoningEffort,
            planItemId: activePlanItem?.id,
          });
        },
        onSubmitChanges: (changes: string) => void submitPlanChanges(changes, activePlanItem?.id),
        onDismiss: () => dismissPlan(activePlanItem?.id),
      }
    : null;

  const composerPlaceholder =
    connectionStatus === "error"
      ? (lastError ?? "Error connecting to Codex. Click to retry.")
      : connectionStatus !== "connected"
        ? "Connecting to Codex..."
        : !thread
          ? "Starting thread..."
          : "Send Codex a message...";

  const activeSubagent = (activeSubagentThreadId
    ? (
        subagents.length > 0
          ? buildCodexBackgroundAgents(subagents)
          : codexRuntime?.runtimeSnapshot?.childThreads?.length
            ? buildCodexBackgroundAgentsFromChildThreads(codexRuntime.runtimeSnapshot.childThreads)
            : buildCodexBackgroundAgentsFromMessages(messages)
      ).find((agent) => agent.id === activeSubagentThreadId)
    : null) ?? null;
  const rawBackgroundAgents = useMemo(
    () => (
      subagents.length > 0
        ? buildCodexBackgroundAgents(subagents)
        : codexRuntime?.runtimeSnapshot?.childThreads?.length
          ? buildCodexBackgroundAgentsFromChildThreads(codexRuntime.runtimeSnapshot.childThreads)
          : buildCodexBackgroundAgentsFromMessages(messages)
    ),
    [codexRuntime?.runtimeSnapshot?.childThreads, messages, subagents],
  );
  const currentThreadId = thread?.id ?? codexRuntime?.runtimeSnapshot?.thread?.id ?? null;
  const effectiveBackgroundAgents = useMemo(
    () => filterOutCurrentCodexThreadAgent(
      rawBackgroundAgents.filter((agent) => !archivedBackgroundAgentIds.includes(agent.id)),
      currentThreadId,
    ),
    [archivedBackgroundAgentIds, currentThreadId, rawBackgroundAgents],
  );
  const effectiveTodoItems = useMemo(
    () => (planItems.length > 0 ? planItems : extractCodexTodoItemsFromMessages(messages)),
    [messages, planItems],
  );
  const reviewChangesFiles = useMemo(
    () => extractReviewChangesFiles(projectCodexSessionPresentation(messages, isStreaming).rows),
    [isStreaming, messages],
  );
  const showReviewChangesDrawer = effectiveTodoItems.length > 0
    && effectiveTodoItems.every((item) => item.status === "completed")
    && reviewChangesFiles.length > 0;
  const codexUsageAlert = useMemo(
    () => getCodexUsageAlert(lastError),
    [lastError],
  );
  useEffect(() => {
    if (!activeSubagentThreadId || subagentThreadMessages[activeSubagentThreadId] || !window.orxa?.codex?.resumeThread) {
      return;
    }
    let cancelled = false;
    setSubagentThreadLoading((current) => ({ ...current, [activeSubagentThreadId]: true }));
    setSubagentThreadErrors((current) => ({ ...current, [activeSubagentThreadId]: null }));
    void window.orxa.codex.resumeThread(activeSubagentThreadId).then((response) => {
      if (cancelled) {
        return;
      }
      const threadRecord = extractThreadFromResumeResponse(response);
      if (!threadRecord) {
        setSubagentThreadErrors((current) => ({ ...current, [activeSubagentThreadId]: "Unable to load agent thread." }));
        return;
      }
      setSubagentThreadMessages((current) => ({
        ...current,
        [activeSubagentThreadId]: buildCodexMessagesFromThread(threadRecord),
      }));
    }).catch((error) => {
      if (cancelled) {
        return;
      }
      const message = error instanceof Error ? error.message : String(error);
      setSubagentThreadErrors((current) => ({ ...current, [activeSubagentThreadId]: message || "Unable to load agent thread." }));
    }).finally(() => {
      if (cancelled) {
        return;
      }
      setSubagentThreadLoading((current) => ({ ...current, [activeSubagentThreadId]: false }));
    });
    return () => {
      cancelled = true;
    };
  }, [activeSubagentThreadId, subagentThreadMessages]);

  const activeSubagentMessages = useMemo(
    () => (
      activeSubagentThreadId
        ? (subagentThreadMessages[activeSubagentThreadId] ?? subagentMessages)
        : []
    ),
    [activeSubagentThreadId, subagentMessages, subagentThreadMessages],
  );
  const subagentPresentationRows = useMemo(
    () => projectCodexSessionPresentation(activeSubagentMessages, false).rows,
    [activeSubagentMessages],
  );
  const subagentTaskText = useMemo(() => {
    const firstUserRow = subagentPresentationRows.find((row) => row.kind === "message" && row.role === "user");
    if (!firstUserRow || firstUserRow.kind !== "message") {
      return null;
    }
    const text = firstUserRow.sections
      .filter((section): section is Extract<(typeof firstUserRow.sections)[number], { type: "text" }> => section.type === "text")
      .map((section) => section.content)
      .join("\n")
      .trim();
    return text || null;
  }, [subagentPresentationRows]);
  const subagentRows = useMemo(
    () => {
      let removedTask = false;
      return subagentPresentationRows.filter((row) => {
        if (row.kind === "message" && row.role === "user" && !removedTask) {
          removedTask = true;
          return false;
        }
        return true;
      });
    },
    [subagentPresentationRows],
  );
  const subagentDetailBody = activeSubagent ? (
    <div className="agent-dock-detail-transcript">
      {subagentRows.length > 0 ? subagentRows.map((row) => (
        <UnifiedTimelineRowView key={row.id} row={row} onOpenFileReference={onOpenFileReference} />
      )) : (
        <p className="agent-dock-detail-state">This background agent has not produced any visible output yet.</p>
      )}
    </div>
  ) : undefined;

  useEffect(() => {
    setArchivedBackgroundAgentIds((current) => current.filter((id) => rawBackgroundAgents.some((agent) => agent.id === id)));
  }, [rawBackgroundAgents]);
  const handleOpenBackgroundAgent = useCallback((threadId: string) => {
    openSubagentThread(threadId);
  }, [openSubagentThread]);
  const handleArchiveBackgroundAgent = useCallback(async (agent: typeof effectiveBackgroundAgents[number]) => {
    if (!window.orxa?.codex || !agent.sessionID) {
      return;
    }
    await window.orxa.codex.archiveThreadTree(agent.id);
    setArchivedBackgroundAgentIds((current) => current.includes(agent.id) ? current : [...current, agent.id]);
    if (activeSubagentThreadId === agent.id) {
      closeSubagentThread();
    }
  }, [activeSubagentThreadId, closeSubagentThread]);
  const toggleTodoOpen = useCallback(() => {
    setTodoOpen((value) => !value);
  }, []);
  const handleOpenReviewChange = useCallback((path: string) => {
    onOpenFileReference?.(path);
  }, [onOpenFileReference]);
  const trailingReasoningId = useMemo(
    () => (isStreaming ? [...messages].reverse().find((msg) => msg.kind === "reasoning")?.id ?? null : null),
    [messages, isStreaming],
  );
  const visibleMessages = useMemo(
    () => messages.filter((msg) => msg.kind !== "reasoning"),
    [messages],
  );
  const trailingReasoning = trailingReasoningId
    ? messages.find((msg) => msg.id === trailingReasoningId && msg.kind === "reasoning")
    : undefined;

  // -- Unavailable state --
  if (!window.orxa?.codex) {
    return (
      <div className="codex-pane">
        <div className="codex-unavailable">
          <Zap size={32} color="var(--text-muted)" />
          <span>Codex is not available. Make sure the codex CLI is installed.</span>
        </div>
      </div>
    );
  }

  return (
    <div className="codex-pane">
      <CodexConversationView
        visibleMessages={visibleMessages}
        trailingReasoning={trailingReasoning}
        isStreaming={isStreaming}
        scrollContainerRef={scrollContainerRef}
        messagesEndRef={messagesEndRef}
        handleScroll={handleScroll}
        showEmptyState={messages.length === 0 && connectionStatus === "connected" && thread !== null}
        onOpenFileReference={onOpenFileReference}
        sessionId={sessionStorageKey}
      />

      {/* Composer area — InteractionCard replaces the composer when questions or plan-implement are active */}
      <div className="codex-composer-area">
        <div className="center-pane-rail center-pane-rail--composer">
          {codexUsageAlert ? (
            <div className="codex-session-alert" role="alert">
              <strong>{codexUsageAlert.title}</strong>
              <span>{codexUsageAlert.body}</span>
            </div>
          ) : null}
          {questionDockProps ? (
            <InteractionCard
              title={questionDockProps.questions[0]?.text ?? "The agent is requesting your input."}
              options={[
                ...(questionDockProps.questions[0]?.options?.map((o, i) => ({
                  id: o.value ?? `opt-${i}`,
                  label: o.label,
                })) ?? []),
                { id: "custom", label: "No, and tell Codex what to do differently", isCustomInput: true },
              ]}
              onSubmit={(optionId, customText) => {
                if (optionId === "custom" && customText) {
                  questionDockProps.onSubmit({ [questionDockProps.questions[0]?.id ?? "q"]: customText });
                } else {
                  questionDockProps.onSubmit({ [questionDockProps.questions[0]?.id ?? "q"]: optionId });
                }
              }}
              onDismiss={questionDockProps.onReject}
            />
          ) : pendingPlanProps ? (
            <InteractionCard
              title="Implement this plan?"
              options={[
                { id: "accept", label: "Yes, implement this plan" },
                { id: "change", label: "No, and tell Codex what to do differently", isCustomInput: true },
              ]}
              onSubmit={(optionId, customText) => {
                if (optionId === "accept") {
                  pendingPlanProps.onAccept();
                } else if (customText) {
                  pendingPlanProps.onSubmitChanges(customText);
                }
              }}
              onDismiss={pendingPlanProps.onDismiss}
            />
          ) : (
            <ComposerPanel
              composer={input}
              setComposer={setInput}
              composerAttachments={[]}
              removeAttachment={() => undefined}
              slashMenuOpen={false}
              filteredSlashCommands={[]}
              slashSelectedIndex={0}
              insertSlashCommand={() => undefined}
              handleSlashKeyDown={() => undefined}
              addComposerAttachments={() => undefined}
              sendPrompt={sendPrompt}
              abortActiveSession={abortActiveSession}
              isSessionBusy={isStreaming}
              isSendingPrompt={false}
              pickImageAttachment={() => undefined}
              hasActiveSession={connectionStatus === "connected" && thread !== null}
              isPlanMode={isPlanMode}
              hasPlanAgent={true}
              togglePlanMode={(enabled) => {
                setIsPlanMode(enabled);
                if (enabled) {
                  const planMode = collaborationModes.find((m) => m.mode === "plan" || m.id === "plan");
                  setSelectedCollabMode(planMode?.id ?? "plan");
                } else {
                  setSelectedCollabMode(undefined);
                }
              }}
              browserModeEnabled={browserModeEnabled}
              setBrowserModeEnabled={setBrowserModeEnabled ?? (() => undefined)}
              hideBrowserToggle={!setBrowserModeEnabled}
              agentOptions={[]}
              onAgentChange={() => undefined}
              permissionMode={permissionMode}
              onPermissionModeChange={onPermissionModeChange}
              compactionProgress={0}
              compactionHint=""
              compactionCompacted={false}
              branchMenuOpen={branchMenuOpen}
              setBranchMenuOpen={setBranchMenuOpen}
              branchControlWidthCh={branchControlWidthCh}
              branchLoading={branchLoading}
              branchSwitching={branchSwitching}
              hasActiveProject={hasActiveProject}
              branchCurrent={branchCurrent}
              branchDisplayValue={branchDisplayValue}
              branchSearchInputRef={branchSearchInputRef}
              branchQuery={branchQuery}
              setBranchQuery={setBranchQuery}
              branchActionError={branchActionError}
              clearBranchActionError={clearBranchActionError}
              checkoutBranch={checkoutBranch}
              filteredBranches={filteredBranches}
              openBranchCreateModal={openBranchCreateModal}
              modelSelectOptions={modelSelectOptions}
              selectedModel={selectedModel}
              setSelectedModel={setSelectedModel}
              selectedVariant={selectedReasoningEffort}
              setSelectedVariant={setSelectedReasoningEffort}
              variantOptions={reasoningEffortOptions}
              variantLabel="Reasoning effort"
              variantEmptyLabel="(default effort)"
              placeholder={composerPlaceholder}
              simpleModelPicker
              backgroundAgents={effectiveBackgroundAgents}
              selectedBackgroundAgentId={activeSubagentThreadId}
              onOpenBackgroundAgent={handleOpenBackgroundAgent}
              onCloseBackgroundAgent={closeSubagentThread}
              onArchiveBackgroundAgent={handleArchiveBackgroundAgent}
              backgroundAgentDetail={subagentDetailBody}
              backgroundAgentTaskText={subagentTaskText}
              backgroundAgentDetailLoading={activeSubagentThreadId ? (subagentThreadLoading[activeSubagentThreadId] ?? false) : false}
              backgroundAgentDetailError={activeSubagentThreadId ? (subagentThreadErrors[activeSubagentThreadId] ?? null) : null}
              backgroundAgentTaggingHint="(@ to tag agents)"
              pendingPermission={permissionDockProps}
              todoItems={effectiveTodoItems.length > 0 ? effectiveTodoItems : undefined}
              todoOpen={todoOpen}
              onTodoToggle={toggleTodoOpen}
              reviewChangesFiles={showReviewChangesDrawer ? reviewChangesFiles : undefined}
              onOpenReviewChange={handleOpenReviewChange}
              queuedMessages={codexQueue}
              sendingQueuedId={codexSendingId}
              onQueueMessage={queueCodexMessage}
              queuedActionKind="steer"
              onPrimaryQueuedAction={async (id) => {
                const item = codexQueue.find((m) => m.id === id);
                if (!item || codexSendingId) return;
                setCodexSendingId(id);
                const sent = await steerMessage(item.text);
                setCodexSendingId(undefined);
                if (!sent) {
                  return;
                }
                setCodexQueue((current) => current.filter((m) => m.id !== id));
              }}
              onEditQueued={editCodexQueued}
              onRemoveQueued={removeCodexQueued}
            />
          )}
        </div>
      </div>
    </div>
  );
}
