import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ModelOption } from '../lib/models'
import type { PermissionMode } from '../types/app'
import type { CodexCollaborationMode, CodexModelEntry } from '@shared/ipc'
import {
  cleanPromptForAutoTitle,
  codexModelsToOptions,
  normalizeGeneratedTitle,
} from './CodexPane.helpers'
import {
  deriveSessionTitleFromPrompt,
  looksAutoGeneratedSessionTitle,
} from '../lib/app-session-utils'

const CODEX_PROVIDER_ID = 'codex'

function useCodexConnectionEffects({
  codexAccessMode,
  connect,
  connectionStatus,
  permissionMode,
  startThread,
  thread,
}: {
  codexAccessMode?: string
  connect: () => Promise<void> | void
  connectionStatus: string
  permissionMode: PermissionMode
  startThread: (options: {
    title: string
    sandbox: 'danger-full-access' | 'read-only'
    approvalPolicy: 'never' | 'on-request'
  }) => Promise<void> | void
  thread: { id?: string | null } | null
}) {
  useEffect(() => {
    let cancelled = false
    const autoConnect = async () => {
      await new Promise(resolve => setTimeout(resolve, 50))
      if (!cancelled) void connect()
    }
    void autoConnect()
    return () => {
      cancelled = true
    }
  }, [connect])

  useEffect(() => {
    if (connectionStatus !== 'connected' || thread) return
    const allowFullAccess = permissionMode === 'yolo-write' || codexAccessMode === 'full-access'
    void startThread({
      title: 'Orxa Code Session',
      sandbox: allowFullAccess ? 'danger-full-access' : 'read-only',
      approvalPolicy: allowFullAccess ? 'never' : 'on-request',
    })
  }, [codexAccessMode, connectionStatus, permissionMode, startThread, thread])
}

function useCodexModelState({
  connectionStatus,
  defaultReasoningEffort,
}: {
  connectionStatus: string
  defaultReasoningEffort?: string
}) {
  const [selectedModel, setSelectedModel] = useState<string | undefined>()
  const [codexModels, setCodexModels] = useState<CodexModelEntry[]>([])
  const [modelSelectOptions, setModelSelectOptions] = useState<ModelOption[]>([])
  const [selectedReasoningEffort, setSelectedReasoningEffort] = useState<string | undefined>()
  const [collaborationModes, setCollaborationModes] = useState<CodexCollaborationMode[]>([])
  const [selectedCollabMode, setSelectedCollabMode] = useState<string | undefined>()

  useEffect(() => {
    if (connectionStatus !== 'connected' || !window.orxa?.codex) return
    void window.orxa.codex.listModels().then(rawModels => {
      setCodexModels(rawModels)
      const options = codexModelsToOptions(rawModels)
      setModelSelectOptions(options)
      if (!selectedModel && options.length > 0) {
        const defaultModel = rawModels.find(model => model.isDefault)
        setSelectedModel(defaultModel ? `${CODEX_PROVIDER_ID}/${defaultModel.model}` : options[0]?.key)
      }
    })
    void window.orxa.codex.listCollaborationModes().then(setCollaborationModes).catch(() => undefined)
  }, [connectionStatus, selectedModel])

  const selectedModelID = useMemo(
    () =>
      selectedModel
        ? selectedModel.startsWith(`${CODEX_PROVIDER_ID}/`)
          ? selectedModel.slice(CODEX_PROVIDER_ID.length + 1)
          : selectedModel
        : undefined,
    [selectedModel]
  )
  const selectedCodexModel = useMemo(
    () => codexModels.find(model => model.model === selectedModelID || model.id === selectedModelID),
    [codexModels, selectedModelID]
  )
  const reasoningEffortOptions = useMemo(
    () => selectedCodexModel?.supportedReasoningEfforts ?? [],
    [selectedCodexModel]
  )
  const defaultCollaborationModeId = useMemo(
    () =>
      collaborationModes.find(mode => {
        const modeId = mode.id.trim().toLowerCase()
        const kind = mode.mode.trim().toLowerCase()
        return modeId === 'default' || kind === 'default'
      })?.id ?? 'default',
    [collaborationModes]
  )

  useEffect(() => {
    if (reasoningEffortOptions.length === 0) {
      if (selectedReasoningEffort !== undefined) setSelectedReasoningEffort(undefined)
      return
    }
    if (selectedReasoningEffort && reasoningEffortOptions.includes(selectedReasoningEffort)) return
    const preferred =
      defaultReasoningEffort && reasoningEffortOptions.includes(defaultReasoningEffort)
        ? defaultReasoningEffort
        : undefined
    setSelectedReasoningEffort(
      preferred ?? selectedCodexModel?.defaultReasoningEffort ?? reasoningEffortOptions[0]
    )
  }, [
    defaultReasoningEffort,
    reasoningEffortOptions,
    selectedCodexModel?.defaultReasoningEffort,
    selectedReasoningEffort,
  ])

  return {
    collaborationModes,
    defaultCollaborationModeId,
    modelSelectOptions,
    reasoningEffortOptions,
    selectedCollabMode,
    selectedModel,
    selectedModelID,
    selectedReasoningEffort,
    setSelectedCollabMode,
    setSelectedModel,
    setSelectedReasoningEffort,
  }
}

function useCodexTitleState({
  onTitleChange,
  sessionStorageKey,
  thread,
  threadName,
  titleLocked,
}: {
  onTitleChange?: (title: string) => void
  sessionStorageKey: string
  thread: { id?: string | null } | null
  threadName?: string
  titleLocked: boolean
}) {
  const titleLockedRef = useRef(titleLocked)
  const threadIdRef = useRef<string | null>(thread?.id ?? null)
  const hasRequestedAutoTitleRef = useRef(false)

  useEffect(() => {
    titleLockedRef.current = titleLocked
  }, [titleLocked])
  useEffect(() => {
    threadIdRef.current = thread?.id ?? null
    hasRequestedAutoTitleRef.current = false
  }, [thread?.id, sessionStorageKey])
  useEffect(() => {
    if (threadName) onTitleChange?.(threadName)
  }, [onTitleChange, threadName])
  useEffect(() => {
    if (threadName && !looksAutoGeneratedSessionTitle(threadName)) {
      hasRequestedAutoTitleRef.current = true
    }
  }, [threadName])

  const requestCodexTitle = useCallback(
    async (targetThreadId: string, requestedTitle: string) => {
      const normalized = normalizeGeneratedTitle(requestedTitle)
      if (!normalized || !window.orxa?.codex) return false
      if (titleLockedRef.current || threadIdRef.current !== targetThreadId) return false
      await window.orxa.codex.setThreadName(targetThreadId, normalized)
      if (titleLockedRef.current || threadIdRef.current !== targetThreadId) return false
      onTitleChange?.(normalized)
      return true
    },
    [onTitleChange]
  )

  const queueAutoTitleGeneration = useCallback(
    (directory: string, prompt: string, existingUserMessageCount: number, targetThreadId: string) => {
      if (hasRequestedAutoTitleRef.current || titleLockedRef.current || !window.orxa?.codex) return
      if (existingUserMessageCount > 0) return
      if (threadName && !looksAutoGeneratedSessionTitle(threadName)) return
      const cleanedPrompt = cleanPromptForAutoTitle(prompt)
      if (!cleanedPrompt) return
      hasRequestedAutoTitleRef.current = true
      void (async () => {
        try {
          const metadata = await window.orxa.codex.generateRunMetadata(directory, cleanedPrompt)
          if (await requestCodexTitle(targetThreadId, metadata.title)) return
        } catch {
          // Fall through to prompt title.
        }
        try {
          await requestCodexTitle(targetThreadId, deriveSessionTitleFromPrompt(prompt))
        } catch {
          // Leave default title if rename fails.
        }
      })()
    },
    [requestCodexTitle, threadName]
  )

  return { queueAutoTitleGeneration }
}

export function useCodexPaneBootstrap(args: {
  codexAccessMode?: string
  connect: () => Promise<void> | void
  connectionStatus: string
  defaultReasoningEffort?: string
  onTitleChange?: (title: string) => void
  permissionMode: PermissionMode
  sessionStorageKey: string
  startThread: (options: {
    title: string
    sandbox: 'danger-full-access' | 'read-only'
    approvalPolicy: 'never' | 'on-request'
  }) => Promise<void> | void
  thread: { id?: string | null } | null
  threadName?: string
  titleLocked: boolean
}) {
  useCodexConnectionEffects(args)
  const modelState = useCodexModelState(args)
  const titleState = useCodexTitleState(args)
  const handleScroll = useCallback(() => {}, [])

  return {
    ...modelState,
    ...titleState,
    handleScroll,
  }
}
